# Generated by Django 4.2.13 on 2024-08-04 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 8, 25, 1, 530843)),
        ),
    ]
