# Generated by Django 4.2.13 on 2024-08-24 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_orderers_familyname_alter_orderers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 24, 19, 16, 5, 327775)),
        ),
    ]
