# Generated by Django 4.2.13 on 2024-08-24 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_storage_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 24, 20, 4, 32, 450526)),
        ),
    ]
