# Generated by Django 4.2.13 on 2024-08-24 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_storage_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='multiplier',
        ),
        migrations.AddField(
            model_name='components',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Количество на складе'),
        ),
        migrations.AddField(
            model_name='components',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.units', verbose_name='Оценочная единица'),
        ),
        migrations.AlterField(
            model_name='components',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Стоимость единицы'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 24, 20, 10, 6, 877029)),
        ),
    ]
